=== ZorbaLua/PRI2018/TP2/manifesto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  vc:minVersion="1.1" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
  <xs:element name="manifesto">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="meta"/>
        <xs:element ref="equipe"/>
        <xs:element ref="resumo"/>
        <xs:element ref="resultado"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="título"/>
        <xs:element minOccurs="0" ref="subtítulo"/>
        <xs:element minOccurs="0" ref="dinício"/>
        <xs:element ref="dfim"/>
        <xs:element ref="supervisor"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="id" type="xs:string"/>
  <xs:element name="título" type="xs:string"/>
  <xs:element name="subtítulo" type="xs:string"/>
  <xs:element name="dinício" type="xs:string"/>
  <xs:element name="dfim" type="xs:string"/>
  <xs:element name="supervisor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nome"/>
        <xs:element ref="email"/>
        <xs:element minOccurs="0" ref="website"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nome" type="xs:string"/>
  <xs:element name="email" type="xs:string"/>
  <xs:element name="website" type="xs:string"/>
  <xs:element name="equipe">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="elemento"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="elemento">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="nome"/>
        <xs:element ref="email"/>
        <xs:element minOccurs="0" ref="website"/>
        <xs:element minOccurs="0" ref="foto"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="foto">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.foto"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.foto">
    <xs:attribute name="path" use="required"/>
  </xs:attributeGroup>
  <xs:element name="resumo">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="para"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="para">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="b"/>
        <xs:element ref="i"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="b">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="i"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="i">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="b"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="resultados">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="resultado"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="resultado">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.resultado"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.resultado">
    <xs:attribute name="path"/>
  </xs:attributeGroup>
</xs:schema>

=== ZorbaLua/PRI2018/TP2/manifesto-tp2.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./manifesto.xsd">
  <meta>
    <id>PG38406</id>
    <título>TP2</título>
    <subtítulo>Relatório de trabalho prático da cadeira de PRI do MEI 2018/19</subtítulo>
    <dinício>25/09/2018</dinício>
    <dfim>01/10/2018</dfim>
    <supervisor>
      <nome>José Carlos Leite Ramalho</nome>
      <email>jcr@di.uminho.pt</email>
      <website>http://www4.di.uminho.pt/~jcr/</website>
    </supervisor>
  </meta>
  <equipe>
    <elemento>
      <id>PG38406</id>
      <nome>Adriano Campinho</nome>
      <email>pg38406@alunos.uminho.pt</email>
      <!-- <website>website1</website> -->
      <!-- <foto path="path0"/> -->
    </elemento>
  </equipe>
  <resumo>
    <para>
      O XML que seja validado pelo schema desenvolvido, em conjunto com processamento via <b>XSLT</b>, permite algumas facilidades no tratamento de informação.
    </para>
    <para>
      O trabalho permitiu o envolvimento do aluno e demonstrar algumas utilizações comuns para exemplificar a potência destas linguagens. Foi criado um exemplo prático (pn) assim como um formato <i>manifesto</i> para que este seja usado nos próximos trabalhos
      práticos da disciplina.
    </para>
  </resumo>
  <resultados>
    <resultado path='manifesto-tp2.xml'>
      manifesto-tp2 (xml)
    </resultado>
    <resultado path='./pn.dtd'>
      pn (dtd)
    </resultado>
    <resultado path='./manifesto.xsl'>
      manifesto (xsl)
    </resultado>
    <resultado path='./manifesto-tp2.html'>
      manifesto-tp2 (html)
    </resultado>
  </resultados>
</manifesto>

=== ZorbaLua/PRI2018/TP4/manifesto-tp4.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./manifesto.xsd">
  <meta>
    <id>PG38406</id>
    <título>TP4</título>
    <subtítulo>Relatório de trabalho prático da cadeira de PRI do MEI 2018/19</subtítulo>
    <dinício>25/09/2018</dinício>
    <dfim>01/10/2018</dfim>
    <supervisor>
      <nome>José Carlos Leite Ramalho</nome>
      <email>jcr@di.uminho.pt</email>
      <website>http://www4.di.uminho.pt/~jcr/</website>
    </supervisor>
  </meta>
  <equipe>
    <elemento>
      <id>PG38406</id>
      <nome>Adriano Campinho</nome>
      <email>pg38406@alunos.uminho.pt</email>
      <!-- <website>website1</website> -->
      <!-- <foto path="path0"/> -->
    </elemento>
  </equipe>
  <resumo>
    <para>
      O XML que seja validado pelo schema desenvolvido, em conjunto com processamento via
      <b>XSLT</b>, permite algumas facilidades no tratamento de informação.
    </para>
    <para>
O trabalho permitiu o envolvimento do aluno e demonstrar algumas utilizações comuns para exemplificar a potência destas linguagens,
neste caso, a criação de índices e a divisão do output em múltiplos ficheiros, e em JS foi criado um servidor suportando a páginas html criadas;
</para>
<para>
Foi criado um site constituído por um indice.html onde se encontra o índice do "Arquivo de Música Digital", e um link para todos as obras armazenadas, estas organizadas em páginas separados.
    </para>
  </resumo>
  <resultados>
    <resultado path='manifesto-tp4.xml'>
      manifesto-tp4 (xml)
    </resultado>
    <resultado path='./index.html'>
      index (html)
    </resultado>
    <resultado>
      obram1-74 (html)
    </resultado>
  </resultados>
</manifesto>

=== ZorbaLua/PRI2018/TP5/manifesto-tp5.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:./manifesto.xsd">
  <meta>
    <id>PG38406</id>
    <título>TP5</título>
    <subtítulo>Relatório de trabalho prático da cadeira de PRI do MEI 2018/19</subtítulo>
    <dinício>25/09/2018</dinício>
    <dfim>01/10/2018</dfim>
    <supervisor>
      <nome>José Carlos Leite Ramalho</nome>
      <email>jcr@di.uminho.pt</email>
      <website>http://www4.di.uminho.pt/~jcr/</website>
    </supervisor>
  </meta>
  <equipe>
    <elemento>
      <id>PG38406</id>
      <nome>Adriano Campinho</nome>
      <email>pg38406@alunos.uminho.pt</email>
      <!-- <website>website1</website> -->
      <!-- <foto path="path0"/> -->
    </elemento>
  </equipe>
  <resumo>
    <para>
      O XML que seja validado pelo schema desenvolvido, em conjunto com processamento via
      <b>XSLT</b>, permite algumas facilidades no tratamento de informação.
    </para>
    <para>
O trabalho permitiu o envolvimento do aluno e demonstrar algumas utilizações comuns para exemplificar a potência destas linguagens,
neste caso, a utilização da linguagem <i>pug</i> e introdução ao <i>json</i> e <i>css</i>;
</para>
<para>
Foi criado um "Arquivo de Música Digital", atravez de ficheiros em json referentes a cada uma das obras;
    </para>
  </resumo>
  <resultados>
    <resultado path='manifesto-tp5.xml'>
      manifesto-tp5 (xml)
    </resultado>
    <resultado path='./index.json'>
      index (json)
    </resultado>
    <resultado path='./index.pug'>
      index (pug)
    </resultado>
    <resultado path='./index.xml'>
      index (xml)
    </resultado>
    <resultado path='./layout.pug'>
      layout (pug)
    </resultado>
    <resultado path='./package.json'>
      package (json)
    </resultado>
    <resultado path='./server.js'>
      server (js)
    </resultado>
    <resultado path='./template.pug'>
      template (pug)
    </resultado>
  </resultados>
</manifesto>
